### ISSUE TITLE
Document the Sinap File Format

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#100]
If we have a document as to this nature already, it should be committed into Git.

For some context, I am rewriting serialization/deserialization, but I'm not sure what the format is.

**Comment by Sheyne** [comment]
Currently just the implementation of the serialization code.

**Comment by Sheyne** [comment]
@slaymaker1907  do you want to do this?

**Comment by RighteousRaichu** [comment]
@slaymaker1907 is this even still necessary?
