### ISSUE TITLE
Fix the Debug Interface

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#105]
I think that while my implementation (minus all the promises which are soon to be removed for the plugin developer) was somewhat elegant, it did not provide a powerful enough interface for custom handling of types.

What it will end up being is likely a combination of the original with the some of the changes that @Sheyne  suggested. One idea that I would really like to do would be to not require type information to be provided in the debug interface directly and instead have the debug property information declared at the same time as regular program inputs and outputs as is being worked on for Beta.

**Comment by slaymaker1907** [comment]
Something really important to talk about is how debugging will interact with graph composition. It seems intuitive that these should work like frames in a normal programming language, but frame information will not be available to interpreters...

One possible solution would be to do a mapping so that it stops on boundary nodes, but then there is the problem of filtering properties based on frame/current graph.

**Comment by Sheyne** [comment]
@slaymaker1907 can I close this?
