### ISSUE TITLE
Properties don't have default values

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#107]
`Accept State` and `Start State` are booleans, but you have to toggle them on off or they get sent to the interpreter as undefineds. I'm working on figuring this out in the general case.

**Comment by RighteousRaichu** [comment]
Related to #91

**Comment by RighteousRaichu** [comment]
@Sheyne I imagine we could do this in graph controller, however, should this be done in core?

For Beta we have just made the interpreter a little more verbose so you don't have to toggle the states in the IDE, so I'm moving this to 1.0.

**Comment by RighteousRaichu** [comment]
Being done in sinap-core and/or sinap-types
