### ISSUE TITLE
ownKeys proxied for drawable listeners and `createX`

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#112]
For `DrawableNode`/`Edge` make sure that the objects returned by the public API only have as ownKeys the values that they want to be saved/undo/redoable.

**Comment by Sheyne** [comment]
Note that edge source/destination should be in ownKeys, but not node parents/children or graph nodes/edges.

**Comment by Sheyne** [comment]
https://github.com/2graphic/sinap-ide/blob/graph-editor-maintenance/app/models/main-graph.ts#L237-L244

**Comment by ilargierdi** [comment]
Are you asking me to fill in the stubs?
