### ISSUE TITLE
Loading files is broken

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#116]
https://github.com/2graphic/sinap-ide/blob/graph-editor-maintenance/app/models/main-graph.ts#L175

It's not legitimate to cast these nulls as any, they apparently get used right away. 

@ilargierdi Do you track sets to the source/destination? If so can we make these arguments optional?

Otherwise I can fix it on my end.

**Comment by ilargierdi** [comment]
Each `DrawableEdge` contains a reference to its source and destination. They're needed for pretty much every computation of edge geometry.

**Comment by Sheyne** [comment]
Even before it's attached to the graph?

**Comment by ilargierdi** [comment]
I'm not sure I like the idea of making source and destination writable. Each drawable edge requires a source and destination when it's constructed, and the fields are readonly to prevent accidentally invalidating an edge by giving it some other pair of nodes. Moving an edge, then, doesn't actually replace the nodes; it destroys the old edge and creates a new one. Is there a compelling reason why you don't want to initialize edges with nodes? Could you not just initialize all the nodes first, then initialize the edges?
