### ISSUE TITLE
Components to display sinap-core object types.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#130]
These need to be editable or readonly. Closely related to #59

These will be used throughout Sinap whenever a generic type is used.

Should be able to display a `Nodes` and `Edges` and in editable mode select new values for them from the graph.

**Comment by Sheyne** [comment]
Should be able to display a `Nodes` and `Edges` and in editable mode select new values for them from the graph.

**Comment by RighteousRaichu** [comment]
Currently there's StringTypeComponent,
        BooleanTypeComponent,
        ObjectTypeComponent,
        NodeTypeComponent,
        ListTypeComponent,
        UnionTypeComponent,
        NumberTypeComponent,

And more can easily/will be added.
