### ISSUE TITLE
Add Support for Dynamic Plugin Registration

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#148]
Initially just scan a special plugins directory and load all files in there with some default name based on the file.

Will also need to initially make sure that default plugins are installed correctly. Not sure exactly how this should be done.

**Comment by slaymaker1907** [comment]
Support is now available in sinap-core to do this and just needs to be incorporated into ide.

**Comment by slaymaker1907** [comment]
@RighteousRaichu what would be the best way to send the kinds of plugins available to the new file dialog? It looks the information flow there is currently unidirectional.

**Comment by RighteousRaichu** [comment]
I could tweak the window service to send an argument to the created window easily. This might be the best option.

Alternatively, the new file dialog can use all the services as the main IDE it wants.

**Comment by RighteousRaichu** [comment]
For example: f4c1c20bd3a7dc3d63add6f90ad08302a0ca848d

**Comment by slaymaker1907** [comment]
Thanks for the help, I'll probably pass it as an argument.
