### ISSUE TITLE
Get path to plugin directory

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#167]
Each loaded plugin should probably contain the path to its folder. This would be helpful for being able to reference images by just a relative URL.

**Comment by slaymaker1907** [comment]
What do you mean exactly? Plugins are already directory based with package.json.

**Comment by Sheyne** [comment]
He means that given some plugin object, he wants to know what directory it came from so he can load assets from that directory.

**Comment by RighteousRaichu** [comment]
Like Sheyne said, a plugins assets should be inside the plugin's folder. And the plugin should be able to reference images/etc by a relative path. The first step is having all plugin objects have a path to their directory.

**Comment by RighteousRaichu** [comment]
@slaymaker1907 is this done?

**Comment by slaymaker1907** [comment]
This is available through InterpreterInfo which is associated with a Plugin.
