### ISSUE TITLE
TSFMT is doing weird shit

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#175]
It seems like it is trying to change every file when I build on my desktop. I have absolutely no idea what it is doing because when I look at the diff, I can not find out what has changed. It works normally on my laptop which is also Windows and this happens even with a fresh clone from GitHub.

**Comment by Sheyne** [comment]
It's probably tslint doing one thing, and tsfmt undoing it. Check the diff with running only one. 

Happens with `<a> b` kind of casts and `accidentalDoubleSemicolons;;`

**Comment by RighteousRaichu** [comment]
I'm assuming it's what sheyne said. If not then we need to fix it instead of removing tsfmt
