### ISSUE TITLE
Structure Components Into Single Angular App

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#18]
Right now, there is pretty much no integration between the components. These should be combined together into a single Angular app.

**Comment by RighteousRaichu** [comment]
I have CJ’s and Dyllon's branches merged into mine and merged into master (2744bb08d391ffca4fb3e2b98fbaef38e29fc617, 66123486df895f7aca90bb9e64acfafc6c3a54c0). Everything’s where it should be layout wise. Next I’m going to work on bringing Sheyne’s interpreter into a service and start hooking that up.

**Comment by RighteousRaichu** [comment]
Some commits with major structural changes: 48efa1154e78f461b75de79b317ce6987144b3b0 3b65fd495233a3a3b63694f72c78401710b4018e
It's all hooked up now for the most part so I'm closing this.
