### ISSUE TITLE
Add Ability for Nodes to Self Reference

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#19]
Right now you can only connect two different nodes.

**Comment by slaymaker1907** [comment]
This fulfills part of issue #2

**Comment by ilargierdi** [comment]
Right now, edges do not make a distinction between source and destination nodes. If both source and destination nodes are equal, the edge should be drawn as a loop. I'm leaving this comment for future reference when I get around to implementing the change. In general, though, the `DrawableGraph.canCreateEdge` interface method should determine whether or not an edge can loop back into its source node.
