### ISSUE TITLE
No such file when booting app.

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#198]
This is related to #195. 

Do we want to address this?
![no-such-file](https://cloud.githubusercontent.com/assets/22377916/23630244/a44e0a28-0277-11e7-9368-598cfeca6dcc.png)

I'm pretty sure this happens when trying to restore the IDE state upon launching and one or more of files associated with a tab no longer exists (in this case, the file name was changed). Not important for beta, but I think this should be cleaned up for 1.0.

**Comment by slaymaker1907** [comment]
I have a helper function in services that works like Promise.all, but it ignores failures instead of failing the whole thing.

**Comment by ilargierdi** [comment]
I'm not really concerned about Sinap breaking from a missing file; it was running fine with the missing tab. I just think that if the IDE tries to launch and load its previous tab state, it should ignore any files that no longer exist for a tab that was previously left open and not print an error to the console.

**Comment by RighteousRaichu** [comment]
We should log the error instead of throwing it, at the very least.

**Comment by slaymaker1907** [comment]
@RighteousRaichu I changed that behavior on the circuits branch that my helper method logs errors in my latest PR.

**Comment by RighteousRaichu** [comment]
kk
