### ISSUE TITLE
Circuit gives incorrect behavior

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#205]
![](https://snag.gy/p3veWV.jpg)

Should be:
 * FF -> S = 0, C = 0
 * FT -> S = 1, C = 0
 * TF -> S = 1, C = 0
 * TT -> S = 0, C = 1

**Comment by slaymaker1907** [comment]
How is this incorrect?

**Comment by Sheyne** [comment]
Look screenshot. FF->sum: T

**Comment by ilargierdi** [comment]
The interpreter logic is incorrect. The diagram, however, is correct.

**Comment by ilargierdi** [comment]
On an unrelated note, this is a perfect use case for our unit test panel. :p

**Comment by Sheyne** [comment]
Unit test currently requires a single boolean output :(

**Comment by RighteousRaichu** [comment]
![screen shot 2017-03-07 at 12 20 40 am](https://cloud.githubusercontent.com/assets/2342524/23645968/01e9369a-02cc-11e7-883c-f4b633538d48.png)
?

**Comment by Sheyne** [comment]
Wow!
