### ISSUE TITLE
Add ability for nodes to have mutual references

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#21]
Right now nodes have additional edges overlap. These should instead adjust so that both edges are visible. This obviously can not be done until issue #20 is accomplished.

**Comment by ilargierdi** [comment]
This behavior should be defined by the `DrawableGraph.canCreateEdge` and `DrawableGraph.createEdge` interface methods.

**Comment by ilargierdi** [comment]
Added support for this in the graph editor from #52 .
