### ISSUE TITLE
Update graph editor input controls

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#223]
Should we make a double click in the graph editor add a node?
The reasoning is that when I want to make many nodes all at once, the current behavior is very slow.

This could in addition to or replace the current behavior.

I believe we also initially talked about a single click to add a node, and click and hold to pan the graph?

**Comment by Sheyne** [comment]
I like for macOS pan and zoom with two fingers and single click makes a node.

**Comment by ilargierdi** [comment]
From our meeting on 3/24:
```
* Double click to create node
* Select multiple by dragging with shift
  - also by pressing down, not pausing, then dragging
* Move canvas by dragging with option (alt)
  - also by pressing down, pausing, then dragging
```

**Comment by ilargierdi** [comment]
#267
