### ISSUE TITLE
Install/Manage plugins

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#226]
There needs to be UI components to install and manage plugins.

Features:
* Install plugin. (Probably from a URL)
  * For groups of plugins, maybe one URL points to multiple plugins, and the UI shows the user which plugins will be installed with checkboxes, all selected by default. (So a user can install all FLAP plugins at once. Or all plugins a professor wants to install.)
* List installed plugins + versions
* Update installed plugins
  * automatically check and prompt to install?
* Remove installed plugins
  * Remove an entire group of installed plugins?

**Comment by slaymaker1907** [comment]
For 1.0, the main feature I am committing to is importing and exporting plugins from directory/zip since converting JFLAP files to sinap files may be difficult #225.
