### ISSUE TITLE
Elements selected by debugger don't show as selected until graph editor gets a mouse event.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#236]
@ilargierdi wanna fix this in the graph editor? Or would it be more semantically correct for the Document Controller to just call .reload() after it changes the selection?

**Comment by ilargierdi** [comment]
I think what's happening is that the editor component is not redrawing after a selection event. I'll take a look into it tonight.

**Comment by ilargierdi** [comment]
I was right; the editor wasn't listing for `select` events. One thing I noticed, though, is when stepping through the print N symbols example, the start state doesn't get highlighted, but everything else does once the active state leaves the start state. I think this may be a separate issue.

**Comment by ilargierdi** [comment]
#241
