### ISSUE TITLE
"circle" and "square" display as ellipses and rectangles?

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#242]

**Comment by ilargierdi** [comment]
In that regard, I was wondering if we want the graph editor to always
handle dynamically resizing nodes, or if that should be left to the plugin
to decide. I was thinking of adding an autosize boolean to the drawable
node properties to support this behavior. What are your thoughts?

**Comment by RighteousRaichu** [comment]
I don't think the plugins ever want to be resizing nodes.

**Comment by ilargierdi** [comment]
That's not what I meant. The idea was to set a flag on the node to tell it
to autosize itself based on its label. If set to false, the plugin could
define a static size, and the node would never resize itself no matter how
long the label was.

**Comment by RighteousRaichu** [comment]
Um if it's trivial that could be a useful feature but I don't see an immediate use for it.

**Comment by ilargierdi** [comment]
#243
