### ISSUE TITLE
Graph Editor View Only Mode

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#259]
Should have a flag that makes it so you can only:
* pan and zoom
* select
* maybe move nodes

**Comment by Sheyne** [comment]
@ilargierdi Is this already implemented?

**Comment by ilargierdi** [comment]
Not yet. How deep do we want view only mode to go? Should we just prevent
new elements from being created/destroyed?

**Comment by RighteousRaichu** [comment]
Yeah I think that'd be fine for now.

**Comment by RighteousRaichu** [comment]
@cj did this.
