### ISSUE TITLE
Graph Editor Cosmetic Changes

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#28]
Non-black borders look weird on my machine. It looks like it always draws a black border before drawing the colored border. 

Selection messes with the look of a node/edge. Makes preview difficult. So for selected entities, draw a blue "shadow" (or larger thickness edge) and then draw the node/edge with no change to its styling on top.

**Comment by ilargierdi** [comment]
I got the second part of your issue fixed but have no idea what you're talking about for the first issue. Pull the latest changes and let me know if it's still happening.
