### ISSUE TITLE
Don't ask to save a newly created file that has no changes.

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#284]
E.g.
* Create new graph
* Do nothing
* Close tab

Shouldn't ask to save the document; it is blank. Likewise, if the user creates a new graph file, makes some changes, then udoes everything and closes the tab, the IDE shouldn't prompt to save the file.

**Comment by RighteousRaichu** [comment]
Marking it as saved if everything is undone is a little more tricky and I'm not promising I'll get there with 1.0

**Comment by ilargierdi** [comment]
That's fine; this is more of a feature request than an issue.

**Comment by ilargierdi** [comment]
#290
