### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#3]
This is the menu responsible for standard menu stuff like saving, loading, exporting, etc. While it is marked for the Prototype, it is an optional feature at that stage but is required for Alpha.

**Comment by RighteousRaichu** [comment]
Basic menu is done in c1ed0f20e6be1f4a3b58681c582246c99f0ffa6f.
We need to make sure it looks nice in linux and windows and then move this issue to Alpha.

**Comment by RighteousRaichu** [comment]
@slaymaker1907 @slaymaker1907 Can you test the menu and make sure it works well in windows and linux? (example: http://electron.atom.io/docs/api/menu/)

**Comment by ilargierdi** [comment]
Menus look good on linux and Windows. The only thing I'd like to mention is that on both OS's, there usually isn't a menu for the application; i.e. `[Snap] [File] [Edit] ...` should be `[File] [Edit] ...` on linux and Windows.
