### ISSUE TITLE
Checkboxes in properties panel for entering booleans

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#31]

**Comment by RighteousRaichu** [comment]
We'll eventually make a custom switch toggle for this, probably..

**Comment by ilargierdi** [comment]
I like the idea of check boxes, but I like the idea of having these properties as part of the graph object as opposed to being on each node object. The graph object property could have a dropdown list for the start node, and a collection of items for the accept nodes.

As an aside, I think for general terminology, we should use "input node" and "output nodes".

**Comment by Sheyne** [comment]
The accepted terminology for DFAs is start state and accept state. Since these properties are part of the graph description language (which I vote we start abbreviating GDL) they can be given domain specific names.

**Comment by RighteousRaichu** [comment]
#58 made these checkboxes, I'd prefer a full width toggle switch so I'm leaving this open.
(my main argument are that checkboxes have a small hit target.)

**Comment by RighteousRaichu** [comment]
This is fine for beta, will make a nicer component later.

**Comment by RighteousRaichu** [comment]
Checkboxes now display the label "true" or "false" next to them, which is also clickable. I'm closing this.
