### ISSUE TITLE
Position node before broadcasting created.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#320]
Can you position a node before you broadcast it's been created.

Currently. The node is created at 0, 0 and the repositioned, triggering two undoable events

**Comment by RighteousRaichu** [comment]
I've just debounced the changes. However, in the future we still want to be careful about extraneous change notifications to keep the app as sleek as possible.

**Comment by ilargierdi** [comment]
Are you talking about pasting?

**Comment by ilargierdi** [comment]
8b4a825
