### ISSUE TITLE
this is undefined in new DrawableEdge... causes weird behavior.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#325]
The most noticeable side effect of this is that when you delete one of a double edge then the other edge stays curved. However, there's potentially deeper problems with this. I'm not sure when this bug was introduced.

(This definitely needs to be fixed before 1.0)

**Comment by RighteousRaichu** [comment]
![screen shot 2017-04-22 at 11 18 42 am](https://cloud.githubusercontent.com/assets/2342524/25306589/7b990592-274d-11e7-8c63-83a34a90fd08.png)

**Comment by ilargierdi** [comment]
@RighteousRaichu Let me know if cf9eb9a at least fixes the curved edge issue.

**Comment by RighteousRaichu** [comment]
Yeah it does.
`this` being undefined may just be a bug in chrome's debugger?

**Comment by ilargierdi** [comment]
I'm going to make the assumption that it is, since the constructor was working just fine.
