### ISSUE TITLE
Save/Load graphs

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#33]
There should be menu actions for saving and loading a graph. Relates to #16 #3. Needs to deal with the bridge between electron and angular to access the file system.

**Comment by RighteousRaichu** [comment]
For the prototype we don't need to interact with Electron, just do something hacky for basic functionality and so we can have prepared graphs to show off for the demo.

**Comment by slaymaker1907** [comment]
Implemented except no support for saving currently open file.

**Comment by ilargierdi** [comment]
Closing this issue and adding a new one for saving the currently open document.
