### ISSUE TITLE
Shadow's don't respect origin

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#331]
![screen shot 2017-04-22 at 5 08 59 pm](https://cloud.githubusercontent.com/assets/2342524/25309011/7010ee66-277e-11e7-8c43-2a7843447fee.png)

**Comment by RighteousRaichu** [comment]
(You can see this with the latest version of the NFA plugin.)

**Comment by ilargierdi** [comment]
8b4a825
