### ISSUE TITLE
Properties Panel Structs are special cased to Points

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#34]
Actually handle structs with arbitrary fields and list the field names. If we're not going to show the field names then position should be a SinapTuple

**Comment by RighteousRaichu** [comment]
I think we may want a specific point type. Because for points I'd prefer to have the row look something like:
Position: X: ---, Y: ---

Not all structs are guaranteed to only have two entries so they should be handled more generically as stated.

**Comment by Sheyne** [comment]
Can we just special case structs with an X and a Y in the display code? 

I was thinking that there would be some kind of function that you would give a `SinapType` and it would return an angular component/HTML. It have a set of rules for how to display a type that could be registered, and it would prefer more specific rules. So you could have a rule for inputting structs, and a rule for inputting structs with numeric x and y fields. 

Or a rule for inputting list of `x` (generic lists an a recursive call on the function), but you could also have a rule for list of images, which just allows for multiple selection on the input dialog.

**Comment by RighteousRaichu** [comment]
I'm still a fan of having a specific point type rather than special casing a generic struct type in the display code.

**Comment by Sheyne** [comment]
@RighteousRaichu close this and open a more general issue on the property panel to handle object types?

**Comment by RighteousRaichu** [comment]
#130
