### ISSUE TITLE
Done button in plugin manager

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#343]
Or @slaymaker1907 thinks this shouldn't be modal. As a bare minimum, knowing cmd+w is the only way out doesn't work.

**Comment by slaymaker1907** [comment]
I think that we should just make this an entirely separate window since unlike the new file modal, it doesn't need to close after every operation and should be dynamically syncing between the two systems.

**Comment by RighteousRaichu** [comment]
It should be a modal windows window with buttons. I can work on it. It's a little difficult because we cache the windows before they're shown.

**Comment by RighteousRaichu** [comment]
Okay, Plugin Manager opens as a full window. It's not cached when it opens, but it can stay open indefinitely with Dyllon's plugin watching.
