### ISSUE TITLE
Mock the tools and file panels

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#35]
For the demo, use screenshots to fake to tools panel and the files panel in the sidebar.

**Comment by RighteousRaichu** [comment]
Also mock bottom panels, as well as ML plugin graph.

**Comment by RighteousRaichu** [comment]
I've mocked the tools and files panel by including an image. On startup a tab is created called machine_learning.sinap, if that tab is viewed an image of the ML graph is displayed. 
(this is all in the demo branch.)

I'm closing this, if someone wants to mockup the bottom panels they can reopen, but I'm not sure it would look good. There's empty panels there to show our vision at least.
