### ISSUE TITLE
Weird things happen if you make a polygon SVG

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#353]
It looks like edge detection does not work and it can't select the node.

**Comment by slaymaker1907** [comment]
It appears that it think the SVG is in a completely different location for some reason.

**Comment by ilargierdi** [comment]
Have you tried setting the origin when defining the node type?

**Comment by slaymaker1907** [comment]
It started working eventually so I think it must have just been a bad install on my part.
