### ISSUE TITLE
If you create a single node on a new document and press enter in the REPL, the error message isn't any good

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#39]

**Comment by RighteousRaichu** [comment]
`TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined.`

**Comment by RighteousRaichu** [comment]
I think what we need to do soon is define generic input/output types for interpreters, as well as an error type. Then when you run the interpreter with bad input/bad graph, the interpreter can return data back in an `error` type and the Input Panel can display the error like an error. 

(Whether or not the interpreter gives a meaningful error is up to the interpreter, but the Input Panel should know it's an error so it can display it like one.)

**Comment by Sheyne** [comment]
Fixed in feab7d3e
