### ISSUE TITLE
Implement zooming and panning in the graph editor component.

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#40]
For input gestures, pinching should affect zoom and two-touch dragging should affect pan.

**Comment by ilargierdi** [comment]
It turns out none of my development machines trigger [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events), so I can't test for multi-touch gestures.

**Comment by Sheyne** [comment]
Googling turns up: http://hammerjs.github.io

In some quick tests on my phone I was partially happy with its handling (except rotate which it really failed on). It allows emulation of touch events (via shift key) so maybe you can use that for dev?

**Comment by Sheyne** [comment]
Also the comments here seem really useful. 

https://github.com/mapbox/mapbox-gl-js/issues/2618

**Comment by ilargierdi** [comment]
I'm closing this issue and making a new one for two-touch input gestures.
