### ISSUE TITLE
Selection needs to change on tab switch

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#43]
The currently selected graph needs to change on tab switch. Currently the previous graph stays selected. Even if the tab was closed.

**Comment by RighteousRaichu** [comment]
I threw CJ in here too, there's some decisions to be made. Preferably I'd like to remember the selection for each tab in it's TabContext. Currently we can do this, but there's no way to set the selection on the graph editor.
(especially since there's type information lost when the selection is set in graphSelectionChanged in the main component.)

**Comment by ilargierdi** [comment]
I just changed the behavior to clear the selection each time the graph object is changed within the editor.

**Comment by RighteousRaichu** [comment]
I think that's fine for the prototype so I'll put this as alpha. But I think we still want it to eventually not "forget" selections as you switch between tabs.

**Comment by ilargierdi** [comment]
I like that idea. I think the idea you have is the correct behavior for selected items. In which case, I'll bring up this point that I keep bringing up about selected components: I think the graph object itself should be keeping track of its selected components, not the editor.

**Comment by RighteousRaichu** [comment]
I agree. Preferably the graph editor keeps track of them, and sends out an event every time it changes (probably still with the new selection set.) 
I still think we need to think about having a method on the graph to call to select a certain element. (In the properties panel, for node types I image we could list the node in a drop down of all other nodes, and have a link next to that that would select the node so you can edit its properties.)

**Comment by RighteousRaichu** [comment]
(and when debugging and probably other scenarios.)

**Comment by ilargierdi** [comment]
I might prefer that the graph object emit the event of selection changes. Let's say the user selects a component directly from the properties panel (or anywhere else for that matter; e.g. cli?). The properties panel should know nothing about the graph editor, so now the properties panel needs to emit an event and the document controller needs to let the editor know about the change. Instead, if the graph object did all the bookkeeping and event emitting with selected components, any UI component that depends on the graph object can subscribe to the selection changed event, and it wouldn't matter where that was coming from, the UI can just update its display based on the event.

**Comment by RighteousRaichu** [comment]
So if I understand, you want the graph editor to keep track of what is currently selected. And when the graph changes it would emit an event with the new selection?

**Comment by ilargierdi** [comment]
No; I think `DrawableGraph` should have methods to get and set the selected items, and the graph object itself would emit all events related to selection changes. This way the graph editor, properties panel, and anything else can subscribe to the selection change event on the graph object.

**Comment by ilargierdi** [comment]
This should be working as part of #52 .
