### ISSUE TITLE
Moving many nodes causes extreme lag.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#46]
If you open 2graph-sinap.sinap and try to select and move all the nodes, it takes many seconds to complete the move.

**Comment by RighteousRaichu** [comment]
This probably caused by updates being sent out for each "step" of the movement and inefficiencies in our propagating the code.

**Comment by slaymaker1907** [comment]
Much improved in Sheyne's branch.

**Comment by ilargierdi** [comment]
Such enhance.

**Comment by RighteousRaichu** [comment]
Sheyne fixed this in #58
