### ISSUE TITLE
Change edge creation behavior.

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#47]
Currently an edge is created by clicking and holding on a node for some delay. Change the implementation so that an edge can be created by clicking from some border region around the edge of a node. The region should be highlighted in some way to indicate that an edge will be created if clicked from within.

**Comment by Sheyne** [comment]
@ilargierdi should this be set to Alpha or Beta? I'm setting it to alpha but we can push it back if we need.

**Comment by ilargierdi** [comment]
I think setting it to alpha is okay. But if I don't manage to get to it in time, I'll just push it back to beta.

**Comment by ilargierdi** [comment]
Add as part of #70
