### ISSUE TITLE
Areas that need redesign after the prototype (now)

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#49]
1. Everything to do with computed properties on PropertiedEntities
2. The interface for a graph that's passed to interpreters
3. graph.ts, specifically the `handler` argument that most constructors take
   and the way that changes are detected and propagated.

**Comment by RighteousRaichu** [comment]
`graph.ts` has lots of helper functions which could probably be located somewhere better. (Or consider bringing in a library that does what we want.) Other than that `graph.ts` is large and could be broken up.

**Comment by slaymaker1907** [comment]
Have had some major updates to graph.ts in Sheyne's branch.

Also, plugin stuff has had significant updates.

**Comment by ilargierdi** [comment]
Is this issue still ongoing, or was it addressed with #58 ?

**Comment by Sheyne** [comment]
Bullet point #1 still needs work.

**Comment by Sheyne** [comment]
I'm closing this issue and making an issue for the specific point.
