### ISSUE TITLE
Fix copy/paste.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#51]
Copy/paste shortcuts behave weird within electron. Without menu items for these, the functionality doesn't work.

**Comment by Sheyne** [comment]
That actually true for all Mac apps.

**Comment by slaymaker1907** [comment]
Seems to work for Windows, but this bug happens in MacOS. Not tested in Linux.

**Comment by ilargierdi** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/Events/copy
