### ISSUE TITLE
Carry over properties from `createEdge` and `createNode`

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#56]
When using the `like` parameter for `createEdge`, the properties of the `like` edge are not carried over to the newly created edge. In particular, the label is not set. I assume the same issue is the case for `createNode`.

**Comment by ilargierdi** [comment]
The implementation of `DrawableEdge` in cf1bc5d now copies drawable properties over from `like`, but properties from plugin types still need to be copied over.

**Comment by Sheyne** [comment]
Doable in main-graph.ts, currently unimplemented.

**Comment by RighteousRaichu** [comment]
I believe this is done/no longer relevant with the way intersection types work.
