### ISSUE TITLE
Flipping coloring on edge moves

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#71]
Currently a shadow is shown where the new edge will be and the old edge is left intact. This doesn't match the behavior of edge creation where the new edge has a different styling. 

I'd like consistant styling between created edges and moved edges and that the old edge become shadowed or in some way greyed out so it's clear which edge is getting moved. 

Proposal:

1. Created edges have the default styling @ 70% opacity
2. Moved edges keep their existing styling @ 70% opacity
3. Why an edge is being moved, the old location is kept, but at 50% opacity. 

What does everyone else think?

Whether or not we go with my suggestions, lets close this before Beta.

**Comment by ilargierdi** [comment]
I think what you describe is how the drawing behavior was originally implemented. It was probably lost during the refactor. I would like to put this in effect, but I'll wait for everyone else to respond before putting it in.

**Comment by RighteousRaichu** [comment]
Why 70% opacity instead of just 100%?

**Comment by ilargierdi** [comment]
@RighteousRaichu Which edge are you talking about? Currently, if you want to move an edge from one node to another, 2 edges are drawn: the original one (which currently is drawn at 100% opacity) and the one being dragged (which has the same properties as an edge being created).

**Comment by RighteousRaichu** [comment]
Sorry I was talking about the proposal. I think new edges or edges being moved should be drawn exactly as they will be (100% opacity) If an edge is being moved then where the old edge was(is?) should be slightly ghosted.

**Comment by Sheyne** [comment]
Maybe visual feedback they're not yet valid.

**Comment by ilargierdi** [comment]
This is currently implemented on 7ade31d.

**Comment by ilargierdi** [comment]
Merged as part of #89.
