### ISSUE TITLE
Static `LineWidth` values?

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#72]
Should the end user only have access to a set of predefined static `lineWidth` values, or should we allow the user to be able to pick arbitrarily sized line widths? Alternatively, we could place a hard cap on the min and max values of line widths.

**Comment by Sheyne** [comment]
Graph editor allows arbitrary. Core.Edge imposes constraints?

**Comment by ilargierdi** [comment]
That's how I was thinking it should be implemented, yes.

**Comment by slaymaker1907** [comment]
Should we close this issue since the question has been answered?

**Comment by ilargierdi** [comment]
I think we should leave this open until it gets explicitly addressed in a PR. I'm not sure if there are any restraints on line widths currently.

**Comment by RighteousRaichu** [comment]
What if we make is a union of acceptable values? (would be displayed as a dropdown.)

**Comment by ilargierdi** [comment]
I like that idea. I was thinking of something you would typically see in like a word document for table borders.

**Comment by Sheyne** [comment]
What about:

`1 | 3 | 5 | number` where it gives you a dropdown of the numeric values or you can enter custom?

**Comment by RighteousRaichu** [comment]
lineWidth and borderWidth were set to type `thin (1px) | medium (2px) | thick (3px) | number`
