### ISSUE TITLE
Clicking on "anchor" creates a self loop

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#75]
I'm not sure if this is desirable in general, but with un-selectable self loops, this is really annoying. I keep trying to select a node and adding a self loop.

**Comment by Sheyne** [comment]
Maybe only show anchor when outside of node radius and keep the click for self loop behavior (which I think is good).

**Comment by ilargierdi** [comment]
Just to clarify: you want the edge threshold of a node to be outside of the
actual node geometry such that the anchor (as well as edge creation) will
only be active if the cursor is outside of the node dimensions?

**Comment by Sheyne** [comment]
Yep.

**Comment by ilargierdi** [comment]
This behavior is now implemented in ff758df.

**Comment by ilargierdi** [comment]
Merged as part of #89.
