### ISSUE TITLE
DFA's interpret wrong.

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#76]
I'm not sure how long this has been a problem, but the interpreter code is pretty broken.
For example:
S---1--->O---1--->A

where S, A and start and accept states, this will report 'true' for '1' and 'false' for 11. There's several other simple DFA's that are also consistently broken.

**Comment by Sheyne** [comment]
Mostly fixed now, except that loops still being broken with nulls.

**Comment by slaymaker1907** [comment]
It should be entirely fixed once my PR is merged. The fix is to basically transmit a serialized graph like the one saved to file and then transform that back to a usable graph in the sandbox rather than creating that graph in the main code.
