### ISSUE TITLE
`Core` design

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#79]
The issue addresses a couple of things.

1. All properties in the PropertyLists are mapped to human keys that contain capitalization and spaces, this is annoying for devs and will probably bug our plugin developers. 
2. Name shadowing: currently there are two name spaces, one for plugin keys one for sinap keys. I see two solutions to this:
     1. put them in the same name-space, if the overlap, have them share data and only show the plugin one in the properties panel. This is useful because plugin creators can opt-in to arbitrary information about nodes and edges, even if it's just cosmetic. This is bad because it is somewhat magical. 
     2. only share name space for keys defined in the built-in Node/Edge types. This means source, destination, label, and edges might be available, but no other properties. This is less magical, so that's good, but its also less flexible. 
3. computed properties
    1. certain properties should be able to be marked as computed (for now limited to string and numeric properties). If they're computed then they should be read only and be updated by some function every-time one of the properties they depend on changes. This is useful for making the label dependent on some other properties such as in the case of turing machines. 
    2. the scope questions above are particularly poignant with computed properties as it would allow the display properties of a node/edge to be computed based on its attributes. 

So if we enable **2.1**, how do we implement it? 

My idea is to add a property (typescript property not `PropertyList` property) to `Core.Element` called backer. The `@DrawableProperty` decorator would automatically convert all fields decorated to a getter/setter pair (this is apparently possible) and have them map to reads and writes on `Core.Element`'s `this.backer`. Plugin properties would also have a mapping from nice names to programmer names and would store their values ask keys on `backer` via their programmer names. Computed values would disable the setters for some of the Drawable/Plugin properties. Since everything is going through the getter/setter mechanism, we can detect events and determine the right time to recompute the computed properties. 

I need support for this soon. It is a blocker for the loading-types branch. 

Thoughts? Ideas?

**Comment by Sheyne** [comment]
This pertains to everyone, so I'll tag you all: @slaymaker1907 @RighteousRaichu @ilargierdi 

I've implemented a lot of the above, but I have some thoughts on the way that matching of field names will occur. Classes will have two labels for each field: the camelCase name and the "Display Name". My question is how this should pertain to inheritance. The code below defines two classes (`A` and `B` where `B` inherits from `A`). What I'm thinking of doing is having (in the case of `A`) `Value` be the "true" name for the field and `val` be the shorthand used to reference it from code. So for all tasks involving inheritance `Value` is the bit that represents the symbol. 

(The below syntax is ugly, I'll probably switch a field definition to look like: `val "Value" String`)

    A = class {
        val =Value: String
    }

    B = class A {
        val2 =Value: String
    }

The other idea is to constrain that if some superclass defines a field with val and Value as the names, then subclasses can't have a val without its human name being Value nor have a Value without its shorthand being val. This would make the above example disallowed. 

The reason I'm thinking that the "Value" form should be the protected part for sure because it is the part that ends up in the GUI and we don't need plugins messing with it. This leaves the `val` part as an optional way to give the field a nicer name from code, and it doesn't matter if the plugins mess with that part because it will only be their code that uses it. 

Sorry if this is rambling and confusing. Let me know what parts I should clarify.

**Comment by ilargierdi** [comment]
I think one way you can avoid display-name collisions is by having the class name display along with the property name iff there is any ambiguity between inherited classes; e.g "A::Value", "B::Value" or something else that looks better but conveys the same information. This may require, or default to, some definition of the class display name.

**Comment by Sheyne** [comment]
Collisions aren't really an issue. A subclass can only override a field iff the new type is a subtype of the old type. Thus it's safe to just use the new type as the Type of the field since it is the most specific. 

The question is whether (for the purposes of overriding) to consider the camelCase name of "Nice Name" to be the one that matches. I feel fairly strongly that the "Nice Name" should have to match, but I'm not sure if we should also require the camelCase name to match, or just discard all be the most specific. The logic for the latter is that the camelCase name is *only* used but the plugin, and it's for their connivence, so if whey want to reference say the destination field of their specific Edge subclass as something else, they can.

**Comment by ilargierdi** [comment]
Just for clarification, where do you anticipate "Nice Name" and `camelCaseName` to be used?

**Comment by Sheyne** [comment]
"Nice Name" shows up in the properties panel and `camelCaseName` is the one used by the plugin to reference fields on the `Node`s, `Edge`s, and `Graph`s that it receives.

**Comment by Sheyne** [comment]
Actually, maybe we don't care if "Nice Name" matches and match only on `camelCaseName`. Originally I thought this was a problem because I thought we didn't want plugins to be able to rename say "Label" in the properties panel, but now that I think about it that seems like reasonable behavior. A DFA plugin can rename "Label" to "Symbol"

**Comment by RighteousRaichu** [comment]
I like the most recent proposal. IE. rename the Label to Voltage for the circuit plugin.
