### ISSUE TITLE
JavaScript Sinap Interfaces

### ISSUE THREAD

**Issue by slaymaker1907** [2graphic/sinap-ide#8]
These interfaces are to be written for easy scripting and use of existing interpreters (for instance a headless Jenkins automated test server). This will be closely related to the plugin API ( issue #1 ) but differs in emphasis. This API will be focused at generating and running Sinap programs using given plugins.

**Comment by RighteousRaichu** [comment]
I think the existence of sinap-core makes this irrelevant.
