### ISSUE TITLE
Fullscreen/Presentation Mode

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#87]
For displaying on a projector screen.

**Comment by RighteousRaichu** [comment]
For beta, having collapsable panels and web page zooming enabled will be good enough.
After Beta we can revisit and see if we want to do more for this.

**Comment by ilargierdi** [comment]
I think with the collapsible panels, zooming, panning, and the native fullscreen mode from electron are a good enough solution to presentation mode.
