### ISSUE TITLE
Edge creation behavior

### ISSUE THREAD

**Issue by Sheyne** [2graphic/sinap-ide#90]
Continuing @RighteousRaichu's comments on #89, I think that we need to find a happy medium. The old behavior was annoying because I made accidental edges all the time (while trying to select nodes). Not they are hard to make. 

One thing that changed that shouldn't have is that when creating an edge, you have to drop it exactly on the edge of a node rather than anywhere on it. This should definitely be fixed. 

Also if possible, allow to hit the anchor points while dragging from slightly inside the node, just not as far in as before. Maybe from 1px in from the edge?

**Comment by Sheyne** [comment]
I'd say make the range that you can create an anchor point 2px wider inwards and 4px wider outwards. And don't apply the same rules while hovering over the new location. That should be anywhere in the node (or maybe even some threshold outside it too).

**Comment by ilargierdi** [comment]
So to clarify, you're asking to shift the threshold back into the node but less than the original implementation, extend the outer threshold by a little more, and only allow dropping on any part of any node other than the source but keep the threshold the same for the source?

**Comment by Sheyne** [comment]
Exactly except that I'd even allow anywhere on the source even once the drag starts. Especially since a single click on an anchor makes a self loop. So:

> you're asking to shift the threshold back into the node but less than the original implementation, extend the outer threshold by a little more, and only allow dropping on any part of any node. ~other than the source but keep the threshold the same for the source~

**Comment by ilargierdi** [comment]
Try 2b13e61 and let me know what you think.

**Comment by Sheyne** [comment]
I like `2.5` better, so I pushed that (see 9a7ce8d).

You should know that squares are completely broken. I don't know if they were before you made the change.

**Comment by ilargierdi** [comment]
#93
