### ISSUE TITLE
Blank canvas bug on resize.

### ISSUE THREAD

**Issue by ilargierdi** [2graphic/sinap-ide#95]
Whenever the app starts up for the first time from `npm start`, and I move the window from one monitor to the other, the `Click to create new graph` doesn't resize to fit the entire space and the blue bar shows up with some additional gray space above the `Click to create new graph` pane.

![image](https://cloud.githubusercontent.com/assets/22377916/22601151/dc6cc812-e9fa-11e6-8839-96932d76b4ad.png)

On a side note, I think it's pretty amazing that I can `Alt + Print Screen` and `Ctrl + V` into the message box and it just works.

**Comment by RighteousRaichu** [comment]
Good catch CJ. I'll get this fixed once I merge the other PRs. 
Apparently the hidden attribute gets overridden by the display css...
http://www.talkingdotnet.com/dont-use-hidden-attribute-angularjs-2/

**Comment by ilargierdi** [comment]
Thanks for the link. I was just starting to use `[hidden]` in the template for the collapsible list component.

**Comment by RighteousRaichu** [comment]
@ilargierdi do you think I should add 
`[hidden] {
  display: none !important;
}`
to the main style sheet that affects all components, or we should just add it to the style sheets for affected components. 

There's a purity vs convenience argument here.

**Comment by ilargierdi** [comment]
I think you should use `ngIf` to check if any tabs are open and display
them appropriately. For the `collapsible-list`, I ended up using the second
proposed solution from the link you posted.

On Feb 3, 2017 11:37 AM, "Daniel James" <notifications@github.com> wrote:

@ilargierdi <https://github.com/ilargierdi> do you think I should add
[hidden] { display: none !important; }
to the main style sheet that affects all components, or we should just add
it to the style sheets for affected components.

There's a purity vs convenience argument here.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/2graphic/sinap-ide/issues/95#issuecomment-277326426>,
or mute the thread

**Comment by RighteousRaichu** [comment]
#97
