### ISSUE TITLE
Canvas has height 0 hack

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#96]
The setTimeout hack in main.component.ts to resize the canvas after it has been hidden doesn't work 100% of the time. We need to investigate this more and have a better solution.

The problem is roughly that a hidden element isn't given a height, so if it's unhidden and resized in the same digest cycle then the size is set to 0.

That's why setTimeout works most of the time, but we can't rely on a race condition.

**Comment by RighteousRaichu** [comment]
@ilargierdi Sorry I've been bugging you so much today, but what do you think 0f2bbe4 to fix this issue? What we want is a notification that the div containing the canvas has been resized but sadly nothing like that exists and I've spent longer than I'm willing to admit looking for a clean way to do it.

What this does instead is basically call resize() any time it could've possibly changed, but only actually resizing if the dimensions have changed.

**Comment by ilargierdi** [comment]
When I first started coding the graph editor, I was trying to figure out a way to have the size of the component be some bound property like `@Input() height` and `@Input() width` or something equivalent. This way the size can change dynamically based on the size of the side and bottom panels and `resize` would not need to be called outside of the editor. I'm not sure if it'll work or how to make it work, but if `resize` works just fine on its hook to `window.resize`, then it probably would.

**Comment by RighteousRaichu** [comment]
The issue is the parent component has no way of knowing when the height and width changes, which would give that proposed solution that same problem we're trying to solve here.

**Comment by ilargierdi** [comment]
I think the main issue I have with 5cf65f8 is the `ngAfterViewChecked`. I tried that, and the overhead wasn't worth it. It might not be so bad with the conditional checks, but I'm skeptical. Is it possible to display the `Click to create a new graph` element on top of everything? Also, side note, the graph editor clears the canvas completely if no graph is set and all input events are unregistered, so it should be safe to capture events over the editor if no tabs are open.

**Comment by ilargierdi** [comment]
I think for now what you have is fine. Going forward, though, once we implement sizable panels for the side and bottom panels, we'll need to revisit this.

**Comment by RighteousRaichu** [comment]
I think I'll give it like an hour max and try to get the overlay working in a way that seems not sketchy and if so we'll go with that, otherwise I'll give up and keep what I have here (I didn't notice any performance impact after adding the conditional checks.)
